[tool.poetry]
name = "openbb-stocks"
version = "0.1.0"
description = "Stocks extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_stocks" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = {version = "^0.1.0a1", source = "test-pypi"}

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
stocks = "openbb_stocks.stocks_router:router"
