[tool.poetry]
name = "openbb-cramer"
version = "1.0.0"
description = "Python custom  Extension for Jim Cramer picks"
authors = ["Marco Mistroni <mmistroni@gmail.com>"]
readme = "README.md"
packages = [{ include = "openbb_cramer" }]

[tool.poetry.dependencies]
python = "<3.12,>=3.9"
openbb-core = "^1.1.2"
openbb-devtools = { version = "^1.0.0b1" }
beautifulsoup4  = { version = "^4.12.3" }
pandas = { version = "^2.2.1" }
finvizfinance = { version = "^0.14.7" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
cramer_provider = "openbb_cramer:cramer_provider"
