[tool.poetry]
name = "openbb-providers"
version = "0.1.1"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_providers" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-sdk-core = { path = "../../core/sdk" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_sdk_core_extension"]
providers = "openbb_providers.providers_router:router"
