[tool.poetry]
name = "openbb-quandl"
version = "0.1.0"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_quandl" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-provider = { path = "../../sdk/provider" }
quandl = ">=3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
quandl = "openbb_quandl:quandl_provider"
