[tool.poetry]
name = "ecb"
version = "0.1.0"
description = ""
authors = ["hjoaquim <h.joaquim@campus.fct.unl.pt>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
