version: '3.8'
services:
  openbbterminal-python:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/openbbterminal-python.dockerfile
    image: "${OPENBBTERMINAL_DOCKER_IMAGE_PREFIX}/openbbterminal-python:${OPENBBTERMINAL_DOCKER_PYTHON_VERSION}"
  openbbterminal-poetry-deps:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/openbbterminal-poetry-deps.dockerfile
      args:
        OPENBBTERMINAL_DOCKER_IMAGE_PREFIX: ${OPENBBTERMINAL_DOCKER_IMAGE_PREFIX}
        OPENBBTERMINAL_DOCKER_PYTHON_VERSION: ${OPENBBTERMINAL_DOCKER_PYTHON_VERSION}
    image: "${OPENBBTERMINAL_DOCKER_IMAGE_PREFIX}/openbbterminal-poetry-deps:${OPENBBTERMINAL_DOCKER_POETRY_DEPS_VERSION}"
  openbbterminal-poetry:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/openbbterminal-poetry.dockerfile
      args:
        OPENBBTERMINAL_DOCKER_IMAGE_PREFIX: ${OPENBBTERMINAL_DOCKER_IMAGE_PREFIX}
        OPENBBTERMINAL_DOCKER_POETRY_DEPS_VERSION: ${OPENBBTERMINAL_DOCKER_POETRY_DEPS_VERSION}
    image: "${OPENBBTERMINAL_DOCKER_IMAGE_PREFIX}/openbbterminal-poetry:${OPENBBTERMINAL_DOCKER_POETRY_VERSION}"
    tty: true
