[tool.poetry]
name = "openbb-obbject1"
version = "0.1.0a1"
description = "test"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_obbject1" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"  # scipy forces python <4.0 explicitly
openbb-core = "^0.1.0a0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"