name: Build and Publish Docker

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        source docker/compose.env 
        echo ${{ env.OPENBBTERMINAL_DOCKER_POETRY_VERSION  }}
        source docker/compose.env && echo ${{ env.OPENBBTERMINAL_DOCKER_POETRY_VERSION  }}
        exit
        source docker/compose.env && docker-compose -f docker/docker-compose.yaml build
        docker tag `docker images -q ghcr.io/openbb-finance/openbbterminal-poetry` ghcr.io/colin99d/openbbterminal-poetry:${{ env.OPENBBTERMINAL_DOCKER_POETRY_VERSION }}
        docker run ghcr.io/colin99d/openbbterminal-poetry:${{ env.OPENBBTERMINAL_DOCKER_POETRY_VERSION }}
        docker push ghcr.io/colin99d/openbbterminal-poetry:${{ env.OPENBBTERMINAL_DOCKER_POETRY_VERSION }}
