name: Build and Push Image
on: [ push ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
        - uses: actions/checkout@v2 # Checking out the repo

        - name: Build and Publish head Docker image
          uses: VaultVulp/gp-docker-action@1.2.0
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
              image-name: my-cool-service # Provide Docker image name
              image-tag: head # Provide Docker image tag
              build-context: docker/openbbterminal-poetry.dockerfile
