name: publish

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        source docker/compose.env && docker-compose -f docker/docker-compose.yaml build
        docker tag `docker images -q ghcr.io/openbb-finance/openbbterminal-poetry` ghcr.io/colin99d/openbb:latest
        docker run ghcr.io/colin99d/openbb:latest
        docker push ghcr.io/colin99d/openbb:latest
