name: Build and Publish Docker

on: workflow_dispatch

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env: 
      OPENBBTERMINAL_DOCKER_GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building the Docker image
        run: |
          source docker/compose.env
          source docker/build.sh
          echo "OPENBBTERMINAL_DOCKER_POETRY_IMAGE=$OPENBBTERMINAL_DOCKER_POETRY_IMAGE" >> $GITHUB_ENV
          
      - name: Publishing the Docker image
        run: |
          docker push "${OPENBBTERMINAL_DOCKER_POETRY_IMAGE}"
