name: Build and Publish Docker

on: workflow_dispatch

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env: 
      OPENBBTERMINAL_DOCKER_GITHUB_REPOSITORY: ${{ github.repository }}
      IMAGE: openbbterminal-poetry

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        source docker/compose.env
        ./docker/build.sh
        docker push "ghcr.io/${OPENBBTERMINAL_DOCKER_GITHUB_REPOSITORY}/${IMAGE}:${OPENBBTERMINAL_DOCKER_RELEASE_VERSION}"
