name: Django Security Check

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install Node modules
        run: npm install

      - name: Run Snyk
        run: snyk test --json > snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Snyk Results
        uses: actions/upload-artifact@v2
        with:
          name: Snyk
          path: snyk-results.json
