[tool.poetry]
name = "openbb"
version = "4.0.0a4"
description = "OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
openbb-core = "^0.1.0a5"

openbb-benzinga = "^0.1.0a4"
openbb-fmp = "^0.1.0a4"
openbb-fred = "^0.1.0a4"
openbb-intrinio = "^0.1.0a4"
openbb-oecd = "^0.1.0a4"
openbb-polygon = "^0.1.0a4"
openbb-sec = "^0.1.0a4"
openbb-tradingeconomics = "^0.1.0a4"
openbb-ultima = "^0.1.0a4"

openbb-crypto = "^0.1.0a4"
openbb-currency = "^0.1.0a4"
openbb-derivatives = "^0.1.0a4"
openbb-economy = "^0.1.0a4"
openbb-equity = "^0.1.0a4"
openbb-etf = "^0.1.0a4"
openbb-fixedincome = "^0.1.0a4"
openbb-index = "^0.1.0a4"
openbb-news = "^0.1.0a4"
openbb-regulators = "^0.1.0a4"

# Community dependencies
openbb-alpha-vantage = { version = "^0.1.0a4", optional = true }
openbb-biztoc = { version = "^0.1.0a4", optional = true }
openbb-cboe = { version = "^0.1.0a4", optional = true }
openbb-ecb = { version = "^0.1.0a4", optional = true }
openbb-finra = { version = "^0.1.0a4", optional = true }
openbb-nasdaq = { version = "^0.1.0a4", optional = true }
openbb-seeking-alpha = { version = "^0.1.0a4", optional = true }
openbb-stockgrid = { version = "^0.1.0a4", optional = true }
openbb-wsj = { version = "^0.1.0a4", optional = true }
openbb-yfinance = { version = "^0.1.0a4", optional = true }

openbb-charting = { version = "^0.1.0a4", optional = true }
openbb-econometrics = { version = "^0.1.0a4", optional = true }
openbb-futures = { version = "^0.1.0a4", optional = true }
openbb-quantitative = { version = "^0.1.0a4", optional = true }
openbb-technical = { version = "^0.1.0a4", optional = true }

[tool.poetry.extras]
alpha_vantage = ["openbb-alpha-vantage"]
biztoc = ["openbb-biztoc"]
cboe = ["openbb-cboe"]
charting = ["openbb-charting"]
ecb = ["openbb-ecb"]
econometrics = ["openbb-econometrics"]
finra = ["openbb-finra"]
futures = ["openbb-futures"]
nasdaq = ["openbb-nasdaq"]
quantitative = ["openbb-quantitative"]
seeking_alpha = ["openbb-seeking-alpha"]
stockgrid = ["openbb-stockgrid"]
technical = ["openbb-technical"]
wsj = ["openbb-wsj"]
yfinance = ["openbb-yfinance"]

all = [
    "openbb-alpha-vantage",
    "openbb-biztoc",
    "openbb-cboe",
    "openbb-charting",
    "openbb-ecb",
    "openbb-econometrics",
    "openbb-finra",
    "openbb-futures",
    "openbb-nasdaq",
    "openbb-quantitative",
    "openbb-seeking-alpha",
    "openbb-stockgrid",
    "openbb-technical",
    "openbb-wsj",
    "openbb-yfinance",
]

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-subtests = "^0.11.0"
pytest-recorder = "^0.2.3"
toml = "^0.10.2"
types-toml = "^0.10.8.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
